package actions

import (
	"bufio"
	"fmt"
	"os"
	"strings"

	"setup-demo/internal/config"
	"setup-demo/internal/logging"
)

const demoHostsINI = `; Demo Ansible inventory generated by "setup --init".
; Replace with real hosts before running "setup --deploy".

[indigo_cluster]
indigo-node1.demo.local ansible_host=192.168.10.11
indigo-node2.demo.local ansible_host=192.168.10.12

[redpanda]
redpanda1.demo.local ansible_host=192.168.10.21

[clickhouse]
clickhouse1.demo.local ansible_host=192.168.10.31

[management]
mgmt1.demo.local ansible_host=192.168.10.41

[all:vars]
ansible_user=deploy
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
`

// Init implements "setup --init": it creates a demo hosts.ini and an empty
// servers.yml, asking for confirmation before overwriting either file that
// already exists.
func Init(hostsPath, serversPath string, log *logging.Logger) error {
	if err := writeWithConfirmation(hostsPath, demoHostsINI, log); err != nil {
		return err
	}
	if err := writeWithConfirmation(serversPath, config.EmptyTemplate(), log); err != nil {
		return err
	}
	log.Printf("Init complete. Edit %s and run 'setup --configure' or edit %s directly.", hostsPath, serversPath)
	return nil
}

func writeWithConfirmation(path, content string, log *logging.Logger) error {
	if _, err := os.Stat(path); err == nil {
		if !confirmOverwrite(path) {
			log.Printf("Skipped %s (kept existing file).", path)
			return nil
		}
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	log.Printf("Wrote %s", path)
	return nil
}

func confirmOverwrite(path string) bool {
	reader := bufio.NewReader(os.Stdin)
	for {
		fmt.Printf("%s already exists. Overwrite? [y/N]: ", path)
		answer, _ := reader.ReadString('\n')
		answer = strings.ToLower(strings.TrimSpace(answer))
		switch answer {
		case "y", "yes":
			return true
		case "", "n", "no":
			return false
		default:
			fmt.Println("Please answer 'y' or 'n'.")
		}
	}
}
