// Package config implements a hand-rolled reader/writer for the fixed
// servers.yml schema used by this demo. A full YAML library is
// intentionally avoided for v1 (see architecture notes); the schema is
// small and fixed, so a minimal line-based parser is sufficient and keeps
// the binary dependency-free.
package config

import (
	"bufio"
	"fmt"
	"os"
	"strings"
)

// Server represents one target host's network configuration, matching the
// fixed servers.yml schema: fqdn, ip, netmask, gw, dns1, dns2.
type Server struct {
	FQDN    string
	IP      string
	Netmask string
	Gateway string
	DNS1    string
	DNS2    string
}

// FakeServers returns a small set of demo servers used whenever a real
// servers.yml is missing or empty, e.g. by "--check" so the tool has
// something meaningful to display out of the box.
func FakeServers() []Server {
	return []Server{
		{FQDN: "indigo-node1.demo.local", IP: "192.168.10.11", Netmask: "255.255.255.0", Gateway: "192.168.10.1", DNS1: "192.168.10.2", DNS2: "8.8.8.8"},
		{FQDN: "indigo-node2.demo.local", IP: "192.168.10.12", Netmask: "255.255.255.0", Gateway: "192.168.10.1", DNS1: "192.168.10.2", DNS2: "8.8.8.8"},
		{FQDN: "redpanda1.demo.local", IP: "192.168.10.21", Netmask: "255.255.255.0", Gateway: "192.168.10.1", DNS1: "192.168.10.2", DNS2: "8.8.8.8"},
		{FQDN: "clickhouse1.demo.local", IP: "192.168.10.31", Netmask: "255.255.255.0", Gateway: "192.168.10.1", DNS1: "192.168.10.2", DNS2: "8.8.8.8"},
		{FQDN: "mgmt1.demo.local", IP: "192.168.10.41", Netmask: "255.255.255.0", Gateway: "192.168.10.1", DNS1: "192.168.10.2", DNS2: "8.8.8.8"},
	}
}

// ParseHostsINI does a minimal parse of an Ansible-style INI inventory
// (as generated by "setup --init"), extracting "<fqdn> ansible_host=<ip>"
// host lines in file order. Group headers, comments, blank lines, and the
// "[all:vars]"-style variable sections are ignored. The result is used to
// pre-fill defaults during "setup --configure" so an operator can accept
// the demo/inventory values with a bare Enter instead of retyping them.
// Fields not present in hosts.ini (netmask, gw, dns1, dns2) are filled
// with the same defaults used elsewhere in this demo.
func ParseHostsINI(path string) ([]Server, error) {
	f, err := os.Open(path)
	if os.IsNotExist(err) {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("open %s: %w", path, err)
	}
	defer f.Close()

	var hosts []Server
	inVarsSection := false

	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())

		switch {
		case line == "" || strings.HasPrefix(line, ";") || strings.HasPrefix(line, "#"):
			continue
		case strings.HasPrefix(line, "["):
			inVarsSection = strings.Contains(line, ":vars]")
			continue
		case inVarsSection:
			continue
		}

		fields := strings.Fields(line)
		if len(fields) == 0 {
			continue
		}

		host := Server{FQDN: fields[0]}
		for _, f := range fields[1:] {
			if ip, ok := strings.CutPrefix(f, "ansible_host="); ok {
				host.IP = ip
			}
		}
		if host.IP == "" {
			// Not a host line we recognize (e.g. a bare var line); skip it.
			continue
		}

		host.Netmask = "255.255.255.0"
		host.Gateway = "192.168.10.1"
		host.DNS1 = "192.168.10.2"
		host.DNS2 = "8.8.8.8"
		hosts = append(hosts, host)
	}
	if err := scanner.Err(); err != nil {
		return nil, fmt.Errorf("read %s: %w", path, err)
	}
	return hosts, nil
}

// EmptyTemplate returns the contents written by "--init" for a brand new
// servers.yml: a valid, empty list.
func EmptyTemplate() string {
	return "servers: []\n"
}

// Save writes the given servers to path using the fixed schema. Existing
// content is fully overwritten by design (this is only ever called after
// the caller has handled any overwrite confirmation).
func Save(path string, servers []Server) error {
	var b strings.Builder
	b.WriteString("servers:\n")
	for _, s := range servers {
		b.WriteString(fmt.Sprintf("  - fqdn: %s\n", s.FQDN))
		b.WriteString(fmt.Sprintf("    ip: %s\n", s.IP))
		b.WriteString(fmt.Sprintf("    netmask: %s\n", s.Netmask))
		b.WriteString(fmt.Sprintf("    gw: %s\n", s.Gateway))
		b.WriteString(fmt.Sprintf("    dns1: %s\n", s.DNS1))
		b.WriteString(fmt.Sprintf("    dns2: %s\n", s.DNS2))
	}
	return os.WriteFile(path, []byte(b.String()), 0o644)
}

// Load reads servers.yml at path using a minimal line-based parser tied to
// the fixed schema above. It returns an empty (nil) slice, with no error,
// if the file doesn't exist or contains no servers — callers are expected
// to fall back to FakeServers() in that case.
func Load(path string) ([]Server, error) {
	f, err := os.Open(path)
	if os.IsNotExist(err) {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("open %s: %w", path, err)
	}
	defer f.Close()

	var servers []Server
	var cur *Server

	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimRight(scanner.Text(), " \t")
		trimmed := strings.TrimSpace(line)

		switch {
		case trimmed == "" || trimmed == "servers:" || trimmed == "servers: []":
			continue
		case strings.HasPrefix(trimmed, "- fqdn:"):
			if cur != nil {
				servers = append(servers, *cur)
			}
			cur = &Server{FQDN: valueAfter(trimmed, "- fqdn:")}
		case cur != nil && strings.HasPrefix(trimmed, "ip:"):
			cur.IP = valueAfter(trimmed, "ip:")
		case cur != nil && strings.HasPrefix(trimmed, "netmask:"):
			cur.Netmask = valueAfter(trimmed, "netmask:")
		case cur != nil && strings.HasPrefix(trimmed, "gw:"):
			cur.Gateway = valueAfter(trimmed, "gw:")
		case cur != nil && strings.HasPrefix(trimmed, "dns1:"):
			cur.DNS1 = valueAfter(trimmed, "dns1:")
		case cur != nil && strings.HasPrefix(trimmed, "dns2:"):
			cur.DNS2 = valueAfter(trimmed, "dns2:")
		}
	}
	if cur != nil {
		servers = append(servers, *cur)
	}
	if err := scanner.Err(); err != nil {
		return nil, fmt.Errorf("read %s: %w", path, err)
	}
	return servers, nil
}

func valueAfter(line, prefix string) string {
	return strings.TrimSpace(strings.TrimPrefix(line, prefix))
}
